apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

# Le namespace n'est pas créé par Kustomize
namespace: client-2
namePrefix: clt2-

replicas:
  - name: hello
    count: 5

images:
  - name: bob2606/hello-http
    newTag: 0.8.33

configMapGenerator:
  - name: hello
    envs:
      - hello.env 
