apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - client-1-ns.yml
  - client-1-quotas.yml

# Le namespace n'est pas créé par Kustomize
namespace: client-1
namePrefix: clt1-

replicas:
  - name: hello
    count: 3

images:
  - name: bob2606/hello-http
    newTag: 0.8.30

configMapGenerator:
  - name: hello
    envs:
      - hello.env 
